---
- name: install node.js and npm
  yum:
    name: npm
    state: present
    enablerepo: epel

- name: install foreever
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ node_npm_modules }}"
